ThisBuild / scalaVersion := "2.13.16"
ThisBuild / organization := "com.example"

val checkNoBom = taskKey[Unit]("Asserts the BOM file was NOT created")
val checkBomExists = taskKey[Unit]("Asserts the BOM file exists")

lazy val root = (project in file("."))
  .enablePlugins(ArtifactBomPlugin)
  .settings(
    name := "sample-app",
    libraryDependencies += "com.typesafe" % "config" % "1.4.3",
    makeBomOnCompile := false,
    checkNoBom := {
      val bomFile = baseDirectory.value / "artifact-bom" / name.value / "pom.xml"
      assert(!bomFile.exists(), s"BOM file should not exist but was found at: $bomFile")
      streams.value.log.info("Confirmed BOM was not generated by compile trigger")
    },
    checkBomExists := {
      val bomFile = baseDirectory.value / "artifact-bom" / name.value / "pom.xml"
      assert(bomFile.exists(), s"BOM file expected at: $bomFile")
      streams.value.log.info("BOM file exists as expected")
    }
  )