name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: sbt

      - name: Publish to Cloudsmith
        env:
          PUBLISH_USER: ${{ secrets.PUBLISH_USER }}
          PUBLISH_PASSWORD: ${{ secrets.PUBLISH_PASSWORD }}
        run: sbt publish
