name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: coursier/setup-action@v3.0.0
        with:
          jvm: temurin:21
          apps: sbt

      - name: Publish to Cloudsmith
        env:
          PUBLISH_USER: ${{ secrets.PUBLISH_USER }}
          PUBLISH_PASSWORD: ${{ secrets.PUBLISH_PASSWORD }}
        run: sbt publish
